In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE  #trained the ML complete set of features
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [2]:
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    selectk_features=fit1.transform(indep_x)
    return selectk_features

In [3]:
def split_scalar(indep_x,dep_y):
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

In [4]:
def cm_prediction(classifier,x_test):  
    y_pred=classifier.predict(x_test)

    # making the confusion matrix
    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,y_pred)
    from sklearn.metrics import accuracy_score 
    from sklearn.metrics import classification_report 
    accuracy=accuracy_score(y_test,y_pred)
    report=classification_report(y_test,y_pred)
    return classifier,accuracy,report,x_test,y_test,cm

In [5]:
def logistic(x_train,y_train,x_test):
    from sklearn.linear_model import LogisticRegression
    classifier= LogisticRegression(random_state = 0)
    classifier.fit(x_train,y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

In [19]:
def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVC
    classifier=SVC(kernel='linear',random_state=0)
    classifier.fit(x_train,y_train)
    classifier,aaccuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return classifier,accuracy,report,x_test,y_test,cm

In [7]:
def svm_NL(x_train,y_train,x_test):     
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(x_train, y_train)
        classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
        return  classifier,accuracy,report,x_test,y_test,cm

In [8]:
def naive(x_train,y_train,x_test):     
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(x_train, y_train)
        classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
        return  classifier,accuracy,report,x_test,y_test,cm

In [9]:
def knn(x_train,y_train,x_test):  
        # Fitting K-NN to the Training set
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(x_train, y_train)
        classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
        return  classifier,accuracy,report,x_test,y_test,cm

In [10]:
def tree(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeClassifier
    classifier=DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    classifier.fit(x_train, y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,accuracy,report,x_test,y_test,cm

In [11]:
def random(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestClassifier
    classifier=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
    classifier.fit(x_train, y_train)
    classifier,accuracy,report,x_test,y_test,cm=cm_prediction(classifier,x_test)
    return  classifier,accuracy,report,x_test,y_test,cm

In [24]:
def selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf):
    dataframe=pd.DataFrame(index=['Chisquare'],columns=['Logistic','SVMl','SVMnl','KNN','Naive','DT','RF'])
    for number,idex in enumerate(dataframe.index):
        dataframe['Logistic'][idex]=acclog[number]
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Naive'][idex]=accnav[number]
        dataframe['DT'][idex]=accdes[number]
        dataframe['RF'][idex]=accrf[number]
    return dataframe

In [13]:
dataset1=pd.read_csv("prep.csv",index_col=None)
df2=dataset1
df2 = pd.get_dummies(df2,dtype=int,drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [14]:
indep_x=df2.drop('classification_yes',axis=1)
dep_y=df2['classification_yes']

In [28]:
kbest=selectkbest(indep_x,dep_y,6)
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]
x_train,x_test,y_train,y_test=split_scalar(kbest,dep_y)

In [30]:
x_train,x_test,y_train,y_test

(array([[ 0.14783985, -0.53161371,  0.66735057,  0.11812851,  0.25241909,
          0.06186409],
        [-0.65587132, -0.42338918, -0.6076989 , -0.17636765, -0.00680427,
          0.06186409],
        [-0.65587132, -0.73453472, -0.77645545, -0.4362172 ,  0.25241909,
         -1.26712075],
        ...,
        [-0.65587132, -0.55866985, -0.85145836, -0.38424729, -0.23413463,
          0.82799677],
        [-0.65587132, -0.80217505, -0.34518871, -0.47086381,  1.59044182,
          0.82799677],
        [-0.65587132, -0.26105237, -0.66395108, -0.34960069,  0.13078066,
         -0.06991074]]),
 array([[-6.55871324e-01, -6.53366316e-01, -2.51435077e-01,
         -4.70863811e-01,  4.95695949e-01, -1.09609075e+00],
        [ 9.51551020e-01,  6.36212327e-02,  2.92336021e-01,
          1.41886893e-02, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -8.83343454e-01, -3.45188714e-01,
         -3.49600686e-01,  1.34716496e+00,  4.43179269e-01],
        [ 1.47839848e-01,  2.01166287e+00, -1.38930712e-01,
         -7.24278287e-02, -5.99049917e-01,  2.28175179e+00],
        [ 9.51551020e-01, -5.85725981e-01, -1.38930712e-01,
         -1.59044347e-01, -7.20688347e-01,  9.56269275e-01],
        [ 2.55897336e+00,  6.36212327e-02, -7.20203265e-01,
         -4.01570597e-01, -6.80427059e-03,  6.18640859e-02],
        [ 1.75526219e+00, -2.61052374e-01,  1.82989568e+00,
          1.48666949e+00, -1.81543421e+00,  5.71451771e-01],
        [-6.55871324e-01,  2.86393109e+00, -7.76455447e-01,
         -4.36217204e-01,  6.17334379e-01,  1.56042646e-02],
        [-6.55871324e-01, -1.52827839e-01, -8.13956902e-01,
         -4.70863811e-01,  6.17334379e-01, -1.55425737e-01],
        [-6.55871324e-01, -1.05920832e+00, -2.70185804e-01,
         -3.49600686e-01,  1.34716496e+00,  1.17005678e+00],
        [-6.55871324e-01,  1.37584373e+00, -7.57704720e-01,
         -3.66923990e-01,  1.59044182e+00, -5.83000742e-01],
        [-6.55871324e-01, -4.63973379e-01,  4.98594024e-01,
          3.43331457e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -7.21006651e-01, -2.70185804e-01,
         -4.70863811e-01,  1.34716496e+00, -2.40940738e-01],
        [ 1.75526219e+00,  3.72972738e+00, -2.32684349e-01,
         -2.97630775e-01, -9.63965206e-01,  6.18640859e-02],
        [-6.55871324e-01, -6.53366316e-01, -6.45200354e-01,
         -4.53540508e-01,  1.22552653e+00, -7.11273243e-01],
        [-6.55871324e-01, -8.02175053e-01, -7.76455447e-01,
         -3.66923990e-01,  1.30780660e-01,  8.70754274e-01],
        [ 9.51551020e-01, -4.91029513e-01,  2.36083839e-01,
          1.41886893e-02, -2.34134628e-01,  6.18640859e-02],
        [-6.55871324e-01, -3.28692709e-01, -3.07687259e-01,
         -3.84247293e-01,  2.52419090e-01, -5.40243242e-01],
        [ 9.51551020e-01, -2.61052374e-01,  8.73608574e-01,
          6.03181011e-01, -1.20724207e+00, -7.96788244e-01],
        [ 1.75526219e+00,  8.88833317e-01,  2.36083839e-01,
          1.18128511e-01, -5.99049917e-01, -3.69213240e-01],
        [-6.55871324e-01, -3.15164642e-01, -7.20203265e-01,
         -3.49600686e-01,  4.95695949e-01, -1.52366575e+00],
        [ 1.47839848e-01, -6.53366316e-01, -5.51446717e-01,
         -2.80307472e-01, -1.08560364e+00, -1.26712075e+00],
        [ 9.51551020e-01, -6.66894383e-01,  3.67338931e-01,
         -1.93690954e-01, -8.42326777e-01,  3.57664268e-01],
        [-6.55871324e-01, -1.00509606e+00, -3.63939442e-01,
         -4.70863811e-01,  1.10388810e+00,  6.14209271e-01],
        [ 2.55897336e+00,  1.02411399e+00,  1.97990150e+00,
          4.12624672e-01, -1.93707264e+00, -1.39539325e+00],
        [-6.55871324e-01, -5.58669847e-01, -8.32707630e-01,
         -3.66923990e-01,  3.74057520e-01,  1.17005678e+00],
        [-6.55871324e-01, -5.04557580e-01, -4.76443807e-01,
         -4.18893900e-01,  1.34716496e+00, -1.18160575e+00],
        [-6.55871324e-01, -7.48062785e-01, -8.13956902e-01,
         -4.01570597e-01,  1.34716496e+00, -8.82303245e-01],
        [-6.55871324e-01, -4.77501446e-01,  6.29849116e-01,
          7.07120833e-01, -2.18034950e+00,  6.18640859e-02],
        [ 9.51551020e-01, -2.49481286e-03, -5.70197444e-01,
         -3.66923990e-01,  3.74057520e-01,  2.83759930e+00],
        [ 9.51551020e-01, -7.48062785e-01, -7.57704720e-01,
         -2.80307472e-01, -6.80427059e-03,  6.18640859e-02],
        [ 2.55897336e+00,  3.20654505e-01,  4.04840386e-01,
          1.78116566e+00, -9.63965206e-01,  6.18640859e-02],
        [-6.55871324e-01, -5.18085647e-01, -1.95182894e-01,
         -4.36217204e-01,  1.30780660e-01,  1.56042646e-02],
        [-6.55871324e-01, -6.26310182e-01, -2.32684349e-01,
         -3.49600686e-01,  1.30780660e-01, -6.99107364e-02],
        [-6.55871324e-01, -3.69276910e-01, -6.26449627e-01,
         -3.49600686e-01,  1.59044182e+00,  4.00421769e-01],
        [-6.55871324e-01, -8.56287320e-01, -8.32707630e-01,
         -3.66923990e-01,  6.17334379e-01, -1.05333325e+00],
        [-6.55871324e-01, -3.96333044e-01, -8.51458357e-01,
         -4.36217204e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -7.34534718e-01, -8.51458357e-01,
         -3.49600686e-01,  8.60611238e-01,  5.28694270e-01],
        [ 9.51551020e-01, -1.05920832e+00,  8.73608574e-01,
          6.89797529e-01, -1.20724207e+00,  1.64038928e+00],
        [-6.55871324e-01, -6.53366316e-01, -2.13933622e-01,
         -3.84247293e-01,  1.71208025e+00,  1.01119265e-01],
        [-6.55871324e-01, -7.48062785e-01, -5.32695989e-01,
         -4.01570597e-01,  4.95695949e-01, -4.97485741e-01],
        [ 1.75526219e+00,  8.07664915e-01,  2.17333111e-01,
         -1.93690954e-01, -1.32888050e+00,  1.68314678e+00],
        [ 2.55897336e+00, -2.49481286e-03, -7.95206175e-01,
         -4.18893900e-01, -1.12496199e-01, -9.67818246e-01],
        [ 9.51551020e-01, -2.49481286e-03, -7.20203265e-01,
         -4.36217204e-01, -5.99049917e-01,  1.72590428e+00],
        [ 1.75526219e+00,  1.97107867e+00,  1.98582384e-01,
          2.04745029e-01, -8.42326777e-01,  3.14906768e-01],
        [-6.55871324e-01, -7.61590852e-01, -7.76455447e-01,
         -4.18893900e-01, -5.99049917e-01, -5.40243242e-01],
        [-6.55871324e-01,  3.07126438e-01, -6.45200354e-01,
          7.77502870e+00, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -2.49481286e-03, -5.48879772e-02,
         -2.43806031e-02,  4.95695949e-01,  1.08454178e+00],
        [-6.55871324e-01, -5.31613713e-01, -5.32695989e-01,
         -3.14954079e-01, -6.80427059e-03,  6.18640859e-02],
        [ 2.55897336e+00,  1.40289986e+00, -3.82690169e-01,
         -3.13461431e-03, -1.08560364e+00,  7.75471185e+00],
        [ 1.75526219e+00,  1.88991027e+00, -4.57693079e-01,
         -2.62984168e-01, -1.69379578e+00,  2.96587180e+00],
        [ 2.55897336e+00, -4.23389178e-01, -8.26785291e-02,
          1.00805207e-01, -8.42326777e-01, -6.68515743e-01],
        [-6.55871324e-01, -7.48062785e-01,  1.04828746e-01,
         -2.80307472e-01, -3.55773058e-01,  1.55487428e+00],
        [-6.55871324e-01, -6.66894383e-01, -4.20191624e-01,
         -4.18893900e-01,  1.22552653e+00,  1.56042646e-02],
        [-6.55871324e-01, -3.42220776e-01, -7.76455447e-01,
         -2.11014257e-01, -5.99049917e-01,  1.34108678e+00],
        [ 1.47839848e-01, -2.49481286e-03,  8.54857846e-01,
          4.81917886e-01, -2.42362636e+00, -7.54030744e-01],
        [-6.55871324e-01, -6.53366316e-01, -5.88948172e-01,
         -3.66923990e-01,  4.95695949e-01, -6.68515743e-01],
        [ 1.75526219e+00, -2.49481286e-03, -8.13956902e-01,
         -4.18893900e-01,  7.38972809e-01,  1.43876766e-01],
        [-6.55871324e-01, -1.05920832e+00, -4.57693079e-01,
         -3.84247293e-01,  1.59044182e+00,  6.56966772e-01],
        [-6.55871324e-01, -2.33996240e-01, -4.20191624e-01,
         -3.84247293e-01,  7.38972809e-01,  4.85936770e-01],
        [-6.55871324e-01, -5.85725981e-01, -4.01440897e-01,
         -4.70863811e-01,  4.95695949e-01, -1.05333325e+00],
        [ 1.75526219e+00, -2.49481286e-03, -5.48879772e-02,
         -2.43806031e-02,  3.74057520e-01,  8.27996773e-01],
        [-6.55871324e-01, -2.49481286e-03, -6.63951082e-01,
         -4.53540508e-01, -3.55773058e-01,  1.76866178e+00],
        [ 1.47839848e-01,  2.36339262e+00, -3.82690169e-01,
         -1.76367650e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -6.12782115e-01, -7.95206175e-01,
         -3.49600686e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01,  1.04205434e-01, -2.88936532e-01,
         -1.41721043e-01, -4.77411488e-01,  8.70754274e-01],
        [ 2.55897336e+00, -7.21006651e-01,  1.92364931e+00,
          7.76414047e-01, -8.42326777e-01, -5.83000742e-01],
        [ 2.55897336e+00, -7.34534718e-01,  1.23579474e-01,
         -3.84247293e-01, -1.08560364e+00,  3.60723430e+00],
        [-6.55871324e-01, -9.91567990e-01, -7.20203265e-01,
         -4.18893900e-01,  1.46880339e+00, -9.67818246e-01],
        [ 9.51551020e-01,  4.04087292e+00, -3.63939442e-01,
         -2.62984168e-01, -7.20688347e-01,  5.71451771e-01],
        [ 1.75526219e+00, -9.50983789e-01, -6.26449627e-01,
         -4.01570597e-01,  2.52419090e-01, -6.68515743e-01],
        [ 1.47839848e-01,  1.44789634e-01, -4.01440897e-01,
         -2.97630775e-01, -5.99049917e-01,  5.71451771e-01],
        [-6.55871324e-01, -8.29231187e-01, -4.20191624e-01,
         -4.70863811e-01,  9.82249668e-01, -3.69213240e-01],
        [-6.55871324e-01, -5.58669847e-01, -7.01452537e-01,
         -4.36217204e-01,  6.17334379e-01,  6.18640859e-02],
        [-6.55871324e-01, -4.23389178e-01, -2.88936532e-01,
         -4.36217204e-01,  1.83371868e+00, -3.69213240e-01],
        [ 1.75526219e+00, -8.42759254e-01, -8.51458357e-01,
         -4.53540508e-01, -7.20688347e-01, -2.40940738e-01],
        [ 1.75526219e+00,  1.98460674e+00,  5.54846206e-01,
          4.12624672e-01, -1.08560364e+00, -5.40243242e-01],
        [ 9.51551020e-01,  5.91215844e-01, -8.13956902e-01,
         -2.62984168e-01, -6.80427059e-03,  5.28694270e-01],
        [-6.55871324e-01, -1.05920832e+00, -5.32695989e-01,
         -4.01570597e-01, -1.20724207e+00,  4.54789931e+00],
        [-6.55871324e-01, -3.15164642e-01, -3.63939442e-01,
         -3.66923990e-01,  1.34716496e+00, -6.68515743e-01],
        [ 2.55897336e+00, -4.09861111e-01,  1.21112167e+00,
          3.60654761e-01, -2.34134628e-01,  5.83617650e-02],
        [ 9.51551020e-01, -5.99254048e-01, -1.95182894e-01,
         -2.80307472e-01,  9.14223086e-03,  6.18640859e-02],
        [-6.55871324e-01, -6.53366316e-01, -4.38942352e-01,
         -3.49600686e-01,  1.59044182e+00, -6.68515743e-01],
        [-6.55871324e-01, -5.45141780e-01, -6.63951082e-01,
         -3.84247293e-01,  4.95695949e-01, -4.54728241e-01],
        [ 2.55897336e+00,  2.14694354e+00, -6.07698899e-01,
         -2.97630775e-01,  9.14223086e-03, -6.68515743e-01],
        [-6.55871324e-01, -2.49481286e-03,  6.67350571e-01,
          5.51211101e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01, -4.23389178e-01, -2.70185804e-01,
         -3.49600686e-01,  7.38972809e-01,  1.43876766e-01],
        [ 1.47839848e-01,  1.31261567e-01, -2.13933622e-01,
         -3.14954079e-01, -6.80427059e-03,  6.18640859e-02],
        [-6.55871324e-01,  9.56473652e-01, -4.57693079e-01,
         -3.32277383e-01, -2.34134628e-01,  6.56966772e-01],
        [ 1.75526219e+00,  1.17733501e-01,  5.54846206e-01,
          1.52775118e-01, -2.78854165e+00,  1.17005678e+00],
        [-6.55871324e-01,  3.20654505e-01, -2.70185804e-01,
         -2.62984168e-01, -1.08560364e+00,  6.18640859e-02],
        [-6.55871324e-01,  1.63287700e+00, -1.76432167e-01,
         -7.24278287e-02, -4.77411488e-01,  6.18640859e-02],
        [-6.55871324e-01, -2.74580441e-01, -4.20191624e-01,
         -4.53540508e-01,  7.38972809e-01, -8.82303245e-01],
        [ 2.55897336e+00, -2.49481286e-03, -2.70185804e-01,
         -3.84247293e-01, -6.80427059e-03,  6.18640859e-02],
        [ 1.75526219e+00,  2.75570656e+00,  1.43613040e+00,
          1.41886893e-02, -9.63965206e-01, -1.05333325e+00],
        [-6.55871324e-01, -3.28692709e-01, -6.82701809e-01,
         -3.49600686e-01, -2.34134628e-01, -7.96788244e-01],
        [-6.55871324e-01,  7.53552648e-01, -5.88948172e-01,
         -3.84247293e-01, -7.20688347e-01,  4.00421769e-01],
        [ 1.47839848e-01, -1.25771705e-01,  5.36095479e-01,
         -3.77812215e-02, -2.34134628e-01, -1.55425737e-01],
        [-6.55871324e-01, -6.53366316e-01, -6.07698899e-01,
         -1.93690954e-01,  4.95695949e-01,  6.18640859e-02],
        [ 1.47839848e-01, -7.21006651e-01, -1.76432167e-01,
         -2.80307472e-01, -6.80427059e-03,  6.18640859e-02]]),
 250    1
 63     1
 312    0
 159    1
 283    0
       ..
 323    1
 192    1
 117    1
 47     0
 172    0
 Name: classification_yes, Length: 299, dtype: int64,
 132    0
 309    1
 334    0
 196    1
 246    1
       ..
 146    1
 135    1
 389    1
 264    1
 363    1
 Name: classification_yes, Length: 100, dtype: int64)

In [31]:
classifier,accuracy,report,x_test,y_test,cm=logistic(x_train,y_train,x_test)
acclog.append(accuracy)

classifier,accuracy,report,x_test,y_test,cm=svm_linear(x_train,y_train,x_test)  
accsvml.append(accuracy)
    
classifier,accuracy,report,x_test,y_test,cm=svm_NL(x_train,y_train,x_test)  
accsvmnl.append(accuracy)
    
classifier,accuracy,report,x_test,y_test,cm=knn(x_train,y_train,x_test)  
accknn.append(accuracy)
    
classifier,accuracy,report,x_test,y_test,cm=naive(x_train,y_train,x_test)  
accnav.append(accuracy)
    
classifier,accuracy,report,x_test,y_test,cm=tree(x_train,y_train,x_test)  
accdes.append(accuracy)
    
classifier,accuracy,report,x_test,y_test,cm=random(x_train,y_train,x_test)  
accrf.append(accuracy)
    
result=selectk_classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Logistic'][idex]=acclog[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMl'][idex]=accsvml[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMnl'][idex]=accsvmnl[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['KNN'][idex]=accknn[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Naive'][idex]=accnav[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['DT'][idex]=accdes[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_10156\1620088425.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['RF'][idex]=accrf[number]

In [27]:
result
#5

          Logistic  SVMl SVMnl   KNN Naive    DT    RF
Chisquare     0.94  0.94  0.95  0.89  0.83  0.96  0.95

In [33]:
result
#6

          Logistic  SVMl SVMnl   KNN Naive    DT    RF
Chisquare     0.95  0.95  0.96  0.93  0.89  0.97  0.97