In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE  #trained the ML complete set of features
import pickle
import matplotlib.pyplot as plt

In [2]:
def selectkbest(indep_x,dep_y,n):
    test=SelectKBest(score_func=chi2,k=n)
    fit1=test.fit(indep_x,dep_y)
    selectk_features=fit1.transform(indep_x)
    return selectk_features

In [3]:
def split_scalar(indep_x,dep_y):
    x_train,x_test,y_train,y_test=train_test_split(indep_x,dep_y,test_size=0.25,random_state=0)
    sc=StandardScaler()
    x_train=sc.fit_transform(x_train)
    x_test=sc.transform(x_test)
    return x_train,x_test,y_train,y_test

In [4]:
def r2_prediction(regressor,x_test,y_test):
    y_pred=regressor.predict(x_test)
    from sklearn.metrics import r2_score
    r2=r2_score(y_test,y_pred)
    return r2

In [5]:
def linear(x_train,y_train,x_test):
    from sklearn.linear_model import LinearRegression
    regressor=LinearRegression()
    regressor.fit(x_train,y_train)
    r2=r2_prediction(regressor,x_test,y_test)
    return r2

In [6]:
def svm_linear(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='linear')
    regressor.fit(x_train,y_train)
    r2=r2_prediction(regressor,x_test,y_test)
    return r2

In [7]:
def svm_nonlinear(x_train,y_train,x_test):
    from sklearn.svm import SVR
    regressor=SVR(kernel='rbf')
    regressor.fit(x_train,y_train)
    r2=r2_prediction(regressor,x_test,y_test)
    return r2

In [8]:
def decision_tree(x_train,y_train,x_test):
    from sklearn.tree import DecisionTreeRegressor
    regressor=DecisionTreeRegressor(random_state=0)
    regressor.fit(x_train,y_train)
    r2=r2_prediction(regressor,x_test,y_test)
    return r2

In [9]:
def random_forest(x_train,y_train,x_test):
    from sklearn.ensemble import RandomForestRegressor
    regressor=RandomForestRegressor(n_estimators=10,random_state=0)
    regressor.fit(x_train,y_train)
    r2=r2_prediction(regressor,x_test,y_test)
    return r2

In [16]:
def selectk_regression(acclin,accsvml,accsvmnl,accdt,accrf):
    dataframe=pd.DataFrame(index=['ChiSquare'],columns=['Linear','SVMl','SVMnl','DT','RF'])
    for number,idex in enumerate(dataframe.index):
        dataframe['Linear'][idex]=acclin[number]
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['DT'][idex]=accdt[number]
        dataframe['RF'][idex]=accrf[number]
    return dataframe

In [11]:
dataset1=pd.read_csv('prep.csv',index_col=None)
df2=dataset1
df2=pd.get_dummies(df2,dtype=int,drop_first=True)
df2

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [12]:
indep_x=df2.drop('classification_yes',axis=1)
dep_y=df2['classification_yes']

In [27]:
kbest=selectkbest(indep_x,dep_y,12)
acclin=[]
accsvml=[]
accsvmnl=[]
accdt=[]
accrf=[]
x_train,x_test,y_train,y_test=split_scalar(kbest,dep_y)

In [28]:
x_train,x_test,y_train,y_test

(array([[ 0.48582539,  0.14783985, -0.36317599, ..., -0.48005487,
          1.34935344, -0.73029674],
        [-1.1250596 , -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        [ 0.85756808, -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        ...,
        [-0.44353133, -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        [-1.37288806, -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        [-0.07178864, -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674]]),
 array([[-0.38157422, -0.65587132, -0.36317599, ...,  2.08309522,
         -0.74109567, -0.73029674],
        [ 0.85756808,  0.95155102, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        [ 1.04343943, -0.65587132, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674],
        ...,
        [ 2.34453884,  0.14783985, -0.36317599, ...,  2.08309522,
          1.34935344,  1.36930639],
        [ 0.54778251, -0.65587132, -0.36317599, ..., -0.48005487,
          1.34935344,  1.36930639],
        [ 1.29126789,  0.14783985, -0.36317599, ..., -0.48005487,
         -0.74109567, -0.73029674]]),
 250    1
 63     1
 312    0
 159    1
 283    0
       ..
 323    1
 192    1
 117    1
 47     0
 172    0
 Name: classification_yes, Length: 299, dtype: int64,
 132    0
 309    1
 334    0
 196    1
 246    1
       ..
 146    1
 135    1
 389    1
 264    1
 363    1
 Name: classification_yes, Length: 100, dtype: int64)

In [25]:
for i in kbest:   
    r2_lin=linear(x_train,y_train,x_test)
    acclin.append(r2_lin)
    r2_sl=svm_linear(x_train,y_train,x_test)    
    accsvml.append(r2_sl)
    r2_NL=svm_nonlinear(x_train,y_train,x_test)
    accsvmnl.append(r2_NL)
    r2_d=decision_tree(x_train,y_train,x_test)
    accdt.append(r2_d)
    r2_r=random_forest(x_train,y_train,x_test)
    accrf.append(r2_r)
    
    
result=selectk_regression(acclin,accsvml,accsvmnl,accdt,accrf)

C:\Users\Sathish\AppData\Local\Temp\ipykernel_14824\1427573149.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['Linear'][idex]=acclin[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_14824\1427573149.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMl'][idex]=accsvml[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_14824\1427573149.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['SVMnl'][idex]=accsvmnl[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_14824\1427573149.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['DT'][idex]=accdt[number]
C:\Users\Sathish\AppData\Local\Temp\ipykernel_14824\1427573149.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dataframe['RF'][idex]=accrf[number]

In [18]:
result
#5

             Linear      SVMl     SVMnl        DT        RF
ChiSquare  0.551985  0.545395  0.749654  0.696181  0.836806

In [26]:
result
#9

             Linear      SVMl     SVMnl        DT        RF
ChiSquare  0.646123  0.602462  0.901819  0.869792  0.919705

In [29]:
result
#10

             Linear      SVMl     SVMnl        DT        RF
ChiSquare  0.646123  0.602462  0.901819  0.869792  0.919705